ShikOfTheRa/scarab-osd

- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Serial.ino
Preparing for new Eeprom write method
> Preparing for new Eeprom write method

- DOCUMENTATION/FirmwareFlashing.md
- DOCUMENTATION/User_Guide.md
Added instructions for flashing the firmware to an OSD, and reference to it in the User Guide.
Note: I'm not sure about how universal the "board" option is... Let me know if I should change this.
Thanks!
> Flashing instructions

- MW_OSD/GlobalVariables.h
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
Added AMP amps to summary display
> Added AMP amps to summary display

- .gitignore
- MW_OSD_GUI/Groups.pde
- MW_OSD_GUI/MW_OSD_GUI.pde
- MW_OSD_GUI/Serial.pde
- MW_OSD_GUI/Simulator.pde
Relocation of GUI  debug to permit more room for serial ports.
Preparation of display are for future startup messages
Hide com passthrough until controllers are ready to avoid questions.
Enable in gui.cfg
Renamed gui.cfg
> GUI debug location move and prep for message window

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Max7456.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
To support cams with dodgy vsync. to be tested. Potentially
significantly reduce timeout timer
> VYSNC timeout

- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
Massive memory savings. Approx 1kb sum form menu optimisations
> Memory savings

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Max7456.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
GPS - checks for GPS data from FC. resets satfix if none received after
x seconds
Really this would beneficial in FC code. nor sure if any value here.
AUTOCAM bugfix - NTSC PAL detect
Noticed probable cam auto detect issue. Code untested
Bugfix to FASTMSP code after testing
Increased ILS glidescope angle following first live test
> Enhanced lost GPS fix detection. ILS widening.

- MW_OSD/Serial.ino
Forgot to add CF write routine ! + noticed bug in menu for other items
> CLEANFLIGHT RC write bugfix

- MW_OSD/Serial.ino
moved checksum to end - thanks to supersopp
> Cleanflight tx checksum typo

- MW_OSD/MW_OSD.ino
- MW_OSD/Serial.ino
Tried to clean up the MSP writes. Reduced a lot of repetition in the code, making it easier to read and saved 458 bytes of program memory. It may be slightly slower and use a bit more dynamic memory due to additional function calls, but I have not tested this. Everything i have tried seems to function as expected, but I can not guarantee that I have not broken anything.
> Msp write functions

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
> Shiki r1.4 dev

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
Bugfix to rcswitch if not using throttle.
More erro message text options.
Changed handler for imroved no sats situation
> Error message and RC switch improvements

- MW_OSD/Config.h
- MW_OSD/GPS.ino
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Serial.ino
Added support for CF1.9 new yaw expo
Bugfix for GPSOSD. Now altitude >330m is possible.
Better NMEA parsing error checking
> Cleanflight 1.9 support - untested

- MW_OSD/GlobalVariables.h
- MW_OSD/Screen.ino
missed items in globalvraiables.
> Missing defines from cleanflight

- MW_OSD/Config.h
> Undo testing config changes

- MW_OSD/Config.h
"-" character cant be used - migrated to "_"
> GPSOSD bugfix "-" define character

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
Option for interrupt driven RSSI - for faster non-blocking screen
updates
> Int driven PWM RSSI implementation

- MW_OSD/MW_OSD.ino
Font upload / vsync display conflict. Added check to disable update when
in font upload mode
> Fonts not uploading when using VSYNC

- MW_OSD/Def.h
- MW_OSD/MW_OSD.ino
> OSD CH support for GPSOSD

- MW_OSD/Config.h
- MW_OSD/Def.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
Can connect PPM signal to OSD and access Menus for configuration at the
field. Untested. May not work :)
> Full OSD Menu / screenswitching support for GPSOSD

- MW_OSD/Screen.ino
thanks to ikura for spotting.
Changed values from base 5 to 10
> BUGFIX: pitch & roll ahi incorrect for large angles

- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
Introduced at suggestion of crazycoder - to enable forced crosshair for
users who do not have accelerometer enabled (therefore no ahi/crosshair
etc)
> Forcecrosshair support

- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
Alarms fire at different times and can lead to disarm or reboot.  In any case, they're pretty much always interesting.
I also refactored the intro code a bit to make it easier to just add a line.
http://gfycat.com/HairyImpeccableBison
> Add Alarms on Intro page and Stats page

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
- OTHER/MW_OSD_GUI_SOURCE/MW_OSD_GUI/ENUM.java
- OTHER/MW_OSD_GUI_SOURCE/MW_OSD_GUI/MW_OSD_GUI.pde
Video voltage alarm can be set via GUI
Video voltage independent of main voltage
> Video voltage changes

- MW_OSD/Credits.txt
- MW_OSD/MW_OSD.ino
> NAZA implementation

- OTHER/MW_OSD_GUI_SOURCE/MW_OSD_GUI/setup.sh
yo @shikofthera, i had a tough time setting up my mac to build the gui, since old versions of processing and controlp5 are required. i've written a little script to lock these dependencies in place to make it easier for other folks to build the mac app.
keep up the great work!
> Mac ui setup

- MW_OSD/Config.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
Added option to disable Flight Summary display
> Added option to disable Flight Summary display

- MW_OSD/Config.h
- MW_OSD/Def.h
Unless intentionally used “HARIKIRI”…
Not a big deal anyways.
> It should be "HARAKIRI"?

- MW_OSD/Config.h
Noticed the minor typo on the line I was uncommenting. Fantastic work by the way!
> Typo fix, "ahve" to "have"

- MW_OSD/Config.h
- MW_OSD/Screen.ino
I like to have GPS position always displayed for recovery purposes. However on typical flights (<50km from home), only a few of the decimal values are required to input in my preferred Android app for recovering crashed aircraft (GPS Status radar... whole #'s populate with current position at the click of a button). So I have been doing this mod on my OSD's to reduce clutter without reduced utility. I am not much of a coder (my first PR! ;). I hope this fit for merge, and I am lost trying to add it to the gui.
> Add an option to display GPS position as ".DDDDDDD".

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/LTM.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
Fixes following live test.
Working :)
> Baseflight Fixedwing final amendments

- MW_OSD/Max7456.ino
Extensive use of `MAX7456_Send()` where appropriate.
Use of pointers instead of indexed array access in loops, where possible and appropriate.
Some readability improvement.
Reduction of 72 bytes from flash under IDE 1.6.8, and 464 bytes under IDE 1.0.6.
@ShikOfTheRa 
I'm not sure what's going on with the IDE 1.0.6; confirmation of the correct operation on your side is advised.
> Max7456.ino cleanup

- MW_OSD/Serial.ino
Did some extensive tidying of serialMenuCommon(), mainly for readability in following areas:
(1) Avoid extra “`if (ROW/COL)`” execution.
(2) Define and use macros for common operations: `ReverseSetting()`, `ModifySetting()` and `ModifySetting16()`.
(3) Use “`+=`“ syntax sugar.
(4) Indentation and leading white space fix.
You may not like the formatting, in which case, just say noop:)
Did try to reduce some code by replacing ignored `read8/16()`s by `skip8/16()` macros also.
> Serial.ino tidying

- MW_OSD/Def.h
as proposed in the original issue #194
someone did implement only half of the changes back then as mentioned in #247
> correct voltagepin for kylin250pdb

- MW_OSD/Config.h
- MW_OSD/Def.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
Added option to adjust some servo settings.
Primarily for fixed wing servo trimming instead of using TX (a no no)
or connecting a GUI.
Requires testing
May require removing some features to operate until memory is freed
> Servo adjust menu option

- MW_OSD/Def.h
- MW_OSD/GlobalVariables.h
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
It is only activated for CLEANFLIGHT190 now, but enabling it for other env should not be too difficult (just say MENU_PID_VEL).
> Add VEL to PID config menu

- MW_OSD/GlobalVariables.h
- MW_OSD/KISS.h
> KISS amperage bugfix >180mah

- MW_OSD/Config.h
- MW_OSD/Def.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
Added one to help with smoother filtering for high throttle punchouts
etc.
Also enabled FC filtering for voltage.
This whole are area some tidying up when have time. Kept in style of
surrounding code for moment.
> Added hysteresis filter

- OTHER/DOCUMENTATION/Camera compatibility
tested on HGLRC F3 V3.1 (AIO FC+PDB+OSD) running mwosd 1.6.4.0 without configuration tweaks.
> added Eachine MC02 AIO compatibility info

- MW_OSD/SerialMAVLINK.ino
In case mavlink mode greater than table
> Mavlink mode limit

- MW_OSD/MW_OSD.ino
> KISS FC Amperage bugfix

- OTHER/DOCUMENTATION/Camera compatibility
added Foxeer HS1189 / Monster / XAT1200M
> Update camera compatibility list

- OTHER/DOCUMENTATION/Camera compatibility
> updated camera compatibility

- MW_OSD/Config.h
- MW_OSD/Def.h
Now only latest FC release is supported (fix #389)
Any suggestion about olders?
- BETAFLIGHT2
- BETAFLIGHT3
- iNAV
- CLEANFLIGHT172
- CLEANFLIGHT180
> add betaflight support for fc_voltage_config option

- MW_OSD/GlobalVariables.h
- MW_OSD/Serial.ino
[MSP_VOLTAGE_METER_CONFIG](https://github.com/betaflight/betaflight/blob/master/src/main/msp/msp_protocol.h#L145) PR for #409
> use MSP_VOLTAGE_METER_CONFIG

- MW_OSD/Config.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
Added to summary/statistics page:
- voltage
- voltageMIN
- rssiMIN
Add MINSUMMARY flag in config.h to hide statistics that are 0.
> Add more statistics and MINSUMMARY 

- MW_OSD/Config.h
- MW_OSD/Def.h
- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
More and more it seems this is a requirement to help troubleshoot. Lets
try - at least during development
> Debug available within OSD menu

- MW_OSD/GlobalVariables.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
12S aupport via analog input. 
Much more S support via Ardu/PX4/mavlink
> 12s support

- MW_OSD/GlobalVariables.h
- MW_OSD/KISS.h
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
Added two submenus for configuration:
- Notch Filter
- Low Pass Filter
> KISS filters setting submenu

- MW_OSD/GlobalVariables.h
- MW_OSD/KISS.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Max7456.ino
- MW_OSD/Screen.ino
- MW_OSD/Serial.ino
In addition to the corrections for home position, this PR contains merge of master branch and a small compilation optimization [ba8c9a3](https://github.com/ShikOfTheRa/scarab-osd/commit/ba8c9a39210c91b6905b84f0ecb5c772dcac792b)
> KISS GPS : home position and heading corrections

- MW_OSD/GPS.ino
I did not find any code references to "u-blox-config.ublox.txt" so i guess this is a obsolte comment and can be removed.
> Cleaned up obsolete comment

- .gitignore
Allows a developer to use PyCharm as editor.
> Added .idea to .gitignore to support PyCharm as editor

- MW_OSD/MW_OSD.ino
Improves readablity, logic is still the same (switched if-statement and divider)
> Removed negation of S_VREFERENCE check to improve readability

- MW_OSD/Config.h
- MW_OSD/MW_OSD.ino
- MW_OSD/Screen.ino
Re-purposes the GUI configurator option to  display Kiss VTX power and channel
> KISS VTX Power / Channel display

- MW_OSD/Config.h
> Typos in Config.h

- MW_OSD/Config.h
Fixed small typo in DUALRSSI comment.
> Fixed small typo in DUALRSSI comment.
