MW_OSD/Config.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Screen.ino

Added option in config.h to provide text warning if satfix is below
minimum required.
Improved function of feature which invokes after loss of sat data for xx
seconds.
Small teak to glidescope display - linked to sidebars so remains hidden
if sidebars not used in screen layout chosen

LOW SAT warning /  glidescope tweak

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Max7456.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino

First implementation of option for faster serial speed updates.
Moved away from fixed timer dependant updates for MSP
Removed unnecessary update requests
Update requests linked to functionality available
Preset speed updates in config.h
Vsync update wait period utilisation migrated to single shot serial
available to remove screen update blocking / remove possible sparklies

MSP serial speed choice introduction

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino

Hello
This PR allows to read the voltage configuration from the FC (cleanflight and baseflight) over MSP.
Included: min cell voltage, max cell voltage and warning cell voltage.
Very helpful when you use multiple lipo configuration e.g. S3 and S4 or lipo and LiFePo.
The voltage warning is now calculated with the "warning cell voltage". The number of cells is not irrelevant.
```c
uint8_t cells = (voltage / MvVBatMaxCellVoltage) + 1;
voltageWarning = cells * MvVBatWarningCellVoltage;
```

Voltage configuration over MSP

---

MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Serial.ino

MSP_RAW_IMU is requested when the mag is enabled.
The response to this is processed thusly:
```
if (cmdMSP==MSP_RAW_IMU)
{
for(uint8_t i=0;i<3;i++)
MwAccSmooth[i] = read16();
}
```
But MwAccSmooth is never used.  This is a global variable, some code, and some time on the serial port to process data that's not used.
I noticed this while bringing up MWOSD on a new type of flight control platform.  Ignoring it doesn't break anything, but not requesting it is even better.

Remove requests for MSP_RAW_IMU

---

MW_OSD/Def.h
MW_OSD/MW_OSD.ino
MW_OSD/Screen.ino

baseflight, cleanflight and Tau Labs (at least) send accumulated current in the analog result.  MWOSD picks this up, but ignores it, although it's likely to be far more accurate than having MWOSD attempt to compute it from the instantaneous current samples it's picking up.
This code just uses the `pMeterSum` value itself if available, else falls back on `amperagesum`, which should work in the case where accumulated current isn't sent along with the analog values.

Accuracy updates for current.

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino

As related to #129, there are many types of alarms the flight controller
may wish to report that aren't necessarily understood by all MWOSD.
This change allows for more flexible alarm reporting.

Adding support for a generic alarming system

---

MW_OSD/MW_OSD.ino

This is an example of why I don't like optional braces.  Had braces been
used here, the code would simply have stopped compiling instead of
yielding unexpected results.

Fix condition to display voltage.

---

MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/Screen.ino
MW_OSD/Serial.ino

This reduces confusion considerably when looking at things like this:
#define MENU9  8 //ALARMS
vs.
#define MENU_ALARMS  8 //ALARMS
(I didn't remove these comments, though they become unnecessary once the
labels are clearer).
There are a lot of things in here that seem to be named with numbers and many have comments that describe what the numbers mean, but I think it's a bit easier if we just call the things what we intend for them to be.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shikofthera/scarab-osd/190)

Renamed menu identifiers to use names.

---

MW_OSD/Screen.ino

I found these while I was working on some other stuff. I don't know the semantics associated with them, but it looks like the && are the correct choice.

Fix logical AND mistakenly coded as bitwise AND

---

MW_OSD/Serial.ino

Move boxname string constants to PROGMEM with strncmp_P and PSTR.
Saves 94 bytes of RAM when BOXNAMES is defined (that's HARAKIRI and MULTIWII_V21 case).
The change is straight forward and it should work, but needs to be tested by HARAKIRI and/or MULTIWII_V21 operators (I only run OP,LP,CF and BTFL myself.)

Move boxname string constants to PROGMEM

---

MW_OSD/Max7456.ino

There is an extra digitalWrite(LOW) at the beginning of MAX_DrawScreen(),  inside the USE_VSYNC case.
Merge two unless the second digitalWrite() is used to fulfill some timing constraint under USE_VSYNC.

Remove extra digitalWrite for USE_VSYNC

---

MW_OSD/Serial.ino

I've not tested this on hardware yet, but when I was doing some work in flight modes, it seemed that this structure simplified things a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shikofthera/scarab-osd/223)

Clean up the box identification code to use a table

---

MW_OSD/MW_OSD.ino

Invalid request (request code 0x00) is sent from request scheduler for MSP_SPEED_{HI,MED} config cases, as an artifact of having REQ_MSP_ATTITUDE in the modeMSPRequest for these cases.
Including it only for the MSP_SPEED_LOW resolves the issue.

Prevent invalid request from being sent

---

MW_OSD/GlobalVariables.h

I'm so badly hallucinated that I can't even test the PR!
Wrong:
`SCREENLAYOUT_DEFAULT [EEPROM_SETTINGS]`
`SCREENLAYOUT_DEFAULT_OSDSW [EEPROM_SETTINGS]`
Right:
`SCREENLAYOUT_DEFAULT [POSITIONS_SETTINGS]`
`SCREENLAYOUT_DEFAULT_OSDSW [POSITIONS_SETTINGS]`
I had to move the `Positions` enum up toward the front also.
P.S.
This PR should have been a big win before the PROGMEM PR, because the yield is 140 bytes or so. Well, it still helps you to stuff LTM code in :)

Fix array sizes for layout defaults

---

MW_OSD/GlobalVariables.h

Not a big deal, sorta tidying.
MwAngle was one of the few variables in `GlobalVariables.h`, and the only variable in the Mw-series, without the specific size.
P.S.
Well, actually, this change will make assignment
`MwAngle[i] = read16();`
valid under 32-bit environment also :)

Be specific on sizeof MwAngle

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino

Enabling USE_MSP_PIDNAMES feature memory footprint is increased by 56 bytes of FLASH space and 56 bytes of RAM.
```
Without USE_MSP_PIDNAMES
Sketch uses 25,086 bytes (81%) of program storage space. Maximum is 30,720 bytes.
Global variables use 1,581 bytes (77%) of dynamic memory, leaving 467 bytes for local variables. Maximum is 2,048 bytes.
With USE_MSP_PIDNAMES
Sketch uses 25,142 bytes (81%) of program storage space. Maximum is 30,720 bytes.
Global variables use 1,637 bytes (79%) of dynamic memory, leaving 411 bytes for local variables. Maximum is 2,048 bytes.
```

This commit fixes issue #235 (MSP_PIDNAMES not implemented)

---

MW_OSD/Def.h

NOCONTROLLER should hide the arm status messages, just like GPSOSD case.

Hide arm status messages if NOCONTROLLER

---

MW_OSD/Def.h
OTHER/DOCUMENTATION/FAQ.md

Noticed this when working with a witespy microminim.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shikofthera/scarab-osd/242)

Fix up references from WITESPY to RTFQ

---

MW_OSD/Config.h
MW_OSD/Max7456.ino

Remove the AUTOCAMWAIT option which became obsolete by continuous signal type checking.

Remove AUTOCAMWAIT

---

MW_OSD/MW_OSD.ino
MW_OSD/Max7456.ino

The code is NOT tested. Intended as a memo.
The AUTOCAM code in MAX7456Stalldetect() is not executed if MAXSTALLDETECT is not defined (MAX7456Stalldetect() is not called unless MAXSTALLDETECT is defined).
Fix this by:
(1) Make a call to MAX7456Stalldetect() if AUTOCAM OR MAXSTALLDETECT is defined, and
(2) (optionally) rename the MAX7456Stalldetect() to MAX7456CheckStatus() because the function now does more than stall detection.

Make AUTOCAM independent from MAXSTALLDETECT

---

MW_OSD/MW_OSD.ino
MW_OSD/Max7456.ino

I’m not too sure if the `cli()` was deliberately put at the beginning of the `MAX7456Setup()`, but …
1. If `USE_VSYNC` is not defined, `sei()` will never get called, which effectively freezes `Serial` operation.
2. General rule is that a non-interrupting periods should be as short as possible, protecting only a section of the code that should be executed atomically.
This PR is for 2.
If there are reasons for `cli()` to protect the entire duration of the `MAX7456Setup()`, `sei()` should be placed after the `#endif` for the `USE_VSYNC` to cover 1.

Only protect where should be atomic

---

MW_OSD/MW_OSD.ino
MW_OSD/Max7456.ino

`AUTOCAM / MAX7456CheckStatus()` was recording the camera type in a local static variable, which caused `MAX7456Setup()` to be called TWICE at startup, once during initialization and once from the first call to `MAX7456CheckStatus()`.
An effect of these two calls was visible as a short loss of sync, occuring one second after the video first become available.
Fixed this by declaring the camera type as global `detectedCamType` that is updated in the `MAX7456Setup()`.
In addition, short (about 1 frame) delay before sensing the cam type was inserted for consistent signal detection.
NOTE: Requires cli()-sei() patch (#277)

Autocam behavior improvement

---

MW_OSD/Def.h
MW_OSD/MW_OSD.ino
MW_OSD/Max7456.ino

After the MAX init change, my Arduino Nano and Adafruit Metro based boards started to experience reset failures. After some try and error, found out that 40msec delay after pulling RESET high solves the problem.
The reset pulse itself was shortened to spec. min. 50msec + alpha.
Note: cli()-sei() patch ( #277) is required to ensure the correct operation of delay().

Consistent reset for duinos

---

MW_OSD/LTM.h
MW_OSD/MW_OSD.ino

As per #288 
Tested with MSP (BF2.9) and LTM (CF1.13.0).

Scale LTM RSSI as they are received (Solves issue #288)

---

MW_OSD/Screen.ino

When `distanceMAX > 9999`, then `altitudeMAX` is over taken by `distanceMAX`.
```
1251 #ifdef LONG_RANGE_DISPLAY
1252       if ((X==1)){
1253         formatDistance(trip,0,2);
1254       }
1255       else if ((X==2) &&(distanceMAX>9999)){
1256         formatDistance(distanceMAX,0,2);
1257       }
1258       else if ((X==3) &&(distanceMAX>9999)){
1259         formatDistance(distanceMAX,0,2);
1260       }
1261       else{
1262         itoa(MenuBuffer[X],screenBuffer,10);
1263       }
```
The `X==3` case should use `altitudeMAX` for formatting in line 1259 at least, and probably use `altitudeMAX` for decision in 1258, too.
Whether to use Km units for max altitude is still under discussion.

MAX ALTITUDE is taken over by MAX DISTANCE

---

MW_OSD/MAVLINK.h

The current MAVLINK code scales attitude incorrectly:
> `MwAngle[0]=(int16_t)(serialbufferfloat(4)*57296/10);`
The correct formula is
>`deci-degree = radian * degree/radian * deci-degree/degree = radian * 57.2958 * 10`
(Original code produces x10 bigger value)
Since Arduino 1.6.8 compiler generates identical code for
`(int16_t)(float_variable*572958/1000*10)`
and
`(int16_t)(float_variable*57.2958*10)`
the latter is selected for clarity.

MAVLINK.h : Fix radian to degree (deci-degree) calculation

---

MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Serial.ino

As per #293
Amperage in MSP_ANALOG is **_signed_** 16-bit integer (unless MultiWii mode is selected in which case the scale is also x10). Handle this correctly.
Proper rounding instead of simple truncation by integer division is also applied.

Handle negative amperage case correctly

---

MW_OSD/Config.h
MW_OSD/Max7456.ino

As per #304.
Software only reset for MAX There are hardwares without MAX’s RESET pin not wired to M328 (e.g.
Airbot MicroOSD v2.3).
For such hardware, relying on hardware reset pin to bring MAX to known state fails, because MAX can be in the middle of an SPI transaction when M328 is reset.
The MAX7456SoftReset() will bring MAX to known state without using the hardware reset.
Needs MAX_SOFTRESET defined in Config.h

Max software reset

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/Max7456.ino
MW_OSD/Serial.ino
MW_OSD/bitarray.h
OTHER/DOCUMENTATION/Canvas_CMS.md

Canvas mode MSP messages are used by FC-side CMS (Configuration Menu System) to draw arbitral text on a screen.
The support is turned on by `CANVAS_SUPPORT` option, and is included as a part of `BETAFLIGHT` option.
This PR also include inverted character support, which is turned on by `INVERTED_CHAR_SUPPORT` option.
MSP canvas mode protocol:
byte: description
0: MSP_CANVAS
1: sub-command
0: Enter/hold canvas mode
Sender must periodically send the enter/hold message:
FC may exist menu mode without notifying for many reasons,
including manual reset or power off/cycle.
We expect the FC to sustain canvasMode by sending non-exit
message within CANVAS_TIMO while the menu mode is active.
1: Exit canvas mode and resume normal OSD operation
2: Clear canvas
3: Draw string at (row,col) with …

Canvas mode support for BF-CMS and inverted char support

---

MW_OSD/GlobalVariables.h
MW_OSD/Serial.ino

Minor maintenance; to be coherent with BF3.1 naming.

Rename MSP_CANVAS to MSP_DISPLAYPORT

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/SerialMAVLINK.ino

Only process packets we use and where length is valid.
Only process packets for matching system and component i.d. default is 1
as per config.h
Outstanding:
verification of armed bit (can force in config.h)
verification of modes and sensor indicators

Mavlink protocol improvements

---

MW_OSD/MW_OSD.ino

Do not use multiwii double speed asynch sampling mode when using
mavlink.

Mavlink baud rate tweak

---

OTHER/DOCUMENTATION/FAQ.md

MacOS Sierra (10.12) does not have "Open apps from anywhere" option anymore.
Added a reference url that tells you to reveal this option.

Added MacOS Sierra "Broken App" workaround in FAQ.md

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/RTC6705.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino

PR status: Reviewing & Testing
- Tested with fabricated hardware (Nano + MAX BOB + FX758-2).
- Should be working (at least to some extent) for Helix.
- Power setting is not tested (no hardware to test).
- Bare stick command is not supported (yet), if genuine did.
- Menu
o Requires SET to be selected (YAW right) for current selection to take effect.
o Top line shows running settings.
o Requires SAVE+EXIT for "running settings" to be stored in EEPROM.

Various mods (Helix should be working)

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino
MW_OSD/RTC6705.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino
MW_OSD/wireMacro.h

PR status: Need review, especially on config menu def restructuring ( 03a97a1 )  @ShikOfTheRa What do you think?
- Bug fix
o Fixed `vtx_transfer` to do the final shifting, given `reg`, `rw` and `data`.
o  Modified `vtx_set_frequency` NOT to shift `data`.
- Finished refactoring using `wireMacro`.
o Better view of which pin is manipulated (may be not a big deal for non-Arduino based hw).
- Restructured config menu definition.
o Separated menu page usage conditionals from order they appear in the config menus.
o It (eventually) allow menu page reordering.
o Menu strings are reviewed and enclosed in the corresponding menu usage conditionals.

Fix for Innova power + refactor + restructure

---

MW_OSD/Config.h
MW_OSD/GlobalVariables.h

- Fixed dependency of MAXPAGE on MENU_VTX (which caused non-VTX platform build to fail)
- Removed freestanding VTX_RC select option (this should be a part of the VTX enabled platforms)

VTX mod 20170221

---

MW_OSD/Config.h
MW_OSD/MW_OSD.ino

add user-configurable values for determining MID and HIGH positions for
layout switching via RCSWITCH_CH setting.
Some RX's offer coarse, non-linear values for channel outputs via toggle switches. 
Ex: OpenLRSng has the option of outputting 8CH+4 'switches' with 1000us range broken up into 4 sections, w/ 'mid' position being above 1600us. This fix provides flexibility in establishing L/M/H switch positions without having to hack into the code.

add defines for RCSWITCH_CH test conditions

---

MW_OSD/Config.h
MW_OSD/Screen.ino

Some people (including myself) don't agree with the sign convention used on some FC's for pitch & roll (ex: pitching nose up produces a 'negative' pitch value, which is counter-intuitive).
Here's a simple patch to allow for flipping the signs of the pitch & roll angles displayed in OSD. It doesn't affect AHI-related routines that use raw pitch & roll values; it simply inverts the sign in the display.
(last PR was broken, tested, woking now)

add config definitions for inverting numeric pitch & roll angles

---

MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino

Add missing request sending for msp_voltage_meter_config (extends #410), related to #409.
What do you think about `#if defined(CLEANFLIGHT) || defined(BETAFLIGHT)`?  Or is `modeMSPRequests |= REQ_MSP_MISC |  REQ_MSP_VOLTAGE_METER_CONFIG;`  better?

send msp_voltage_meter_config request

---

OTHER/DOCUMENTATION/Calibration.md

Has anyone else had a problem with current from FC showing several factors of 10 greater than it should be?  
I wasn't able to calibrate properly until I set the MWOSD amperage settings as enclosed.  The default `Amps Adjust` of 400 seemed to be affecting the values.  Setting this to `1` fixed it for me.

add FC current sensor notes

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/MW_OSD.ino
MW_OSD/sbus.cpp
MW_OSD/sbus.h

This PR adds support for connecting S.Bus capable receivers directly to MWOSD adding the same functionality as PPM_CONTROL.
I simply couldn't get the analog RSSI readings working with my FrSky XM+ receiver so instead I loaded a firmware to the RX that added RSSI to channel 16 and then adding S.Bus support in MWOSD.
Tested with a FrSky XM plus (XM+) receiver.

Make it possible to connect S.Bus capable receivers directly to MWOSD

---

MW_OSD/GlobalVariables.h
MW_OSD/KISS.h
MW_OSD/MW_OSD.ino
MW_OSD/Serial.ino

Added memory protection if size of kiss informations or greater than buffer.
I just set indexes to simplify reading

Memory leak with KISS 1.3RC39b

---

MW_OSD/Def.h
MW_OSD/GlobalVariables.h
MW_OSD/KISS.h
MW_OSD/MW_OSD.ino
MW_OSD/Screen.ino
MW_OSD/Serial.ino

Use a submenu because otherwise it would be necessary to completely reconfigure the card or send x commands.
Each category has its order for its configuration.

Submenu for KISS configurations

---

MW_OSD/GlobalVariables.h

Was defined twice (three lines above/ below).

Removed dublicated definition of DEF_S_TX_TYPE

---

MW_OSD/Config.h
MW_OSD/Def.h
MW_OSD/GPS.ino
MW_OSD/GlobalVariables.h
MW_OSD/MW_OSD.ino

For use with other OSD
Provides GPS tracking for use with Sentinel AAT tracker
Auto detects GPS baud rate. 
Single wire from GPS required

Add Sentinel AAT module target

---

MW_OSD/GlobalVariables.h
MW_OSD/KISS.h
MW_OSD/MW_OSD.ino
MW_OSD/Serial.ino

The configuration is permanently reloaded during the configuration and therefore one cannot edit the values (PID etc..)

KISS : request settings if needed
